name: shoppe_customer
description: Pexa.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 4.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.5
  shared_preferences: ^2.0.6
  #  connectivity: ^3.0.6
  connectivity_plus: ^5.0.2
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  flutter_local_notifications: ^16.3.2
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  geolocator: ^11.0.0
  geocoding: ^2.0.5
  location: ^5.0.3
  google_maps_flutter: ^2.2.1
  #  google_place: ^0.4.7
  # flutter_carousel_slider: ^1.1.0
  carousel_slider: ^4.1.1
  http: ^1.2.1
  pointer_interceptor: ^0.10.1
  readmore: ^2.2.0
  get_storage: ^2.0.3
  permission_handler: ^11.3.0
  hexcolor: ^3.0.1
  google_fonts: ^6.1.0
  flutter_rounded_date_picker: ^3.0.2
  device_info_plus: ^9.1.2
  cached_network_image: ^3.2.2
  flutter_cache_manager: ^3.3.0
  new_version_plus: ^0.0.3
  upgrader: ^9.0.0
  url_launcher: ^6.1.5
  flutter_smart_dialog: ^4.5.4+2
  loading_animation_widget: ^1.2.0+2
  razorpay_flutter: ^1.3.6
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  pull_to_refresh_flutter3: ^2.0.1
  webview_flutter: ^4.7.0
  animations: ^2.0.7
  firebase_dynamic_links: ^5.0.8
  firebase_analytics: ^10.0.7
  font_awesome_flutter: ^10.3.0
  share_plus: ^7.2.2
  youtube_player_flutter: ^9.0.0
  persistent_bottom_nav_bar: ^5.0.2
  google_places_autocomplete_text_field: ^0.1.3
  http_parser: ^4.0.2
  path: ^1.9.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/menu/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/image/menu/
    - assets/image/icons/
    - assets/image/error_icons/
    - assets/image/drawer/
    - assets/carSpa/
    - assets/serviceImage/
    - assets/serviceImageCircle/
    - assets/notification.mp3


