// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO5oJnzVjmM2fF8jj9aNdjJGli6DuEifw',
    appId: '1:968510000223:web:d6d842cceebc871759dfea',
    messagingSenderId: '968510000223',
    projectId: 'carclenx',
    authDomain: 'carclenx.firebaseapp.com',
    databaseURL: 'https://carclenx.firebaseio.com',
    storageBucket: 'carclenx.appspot.com',
    measurementId: 'G-JLF6R7VX8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwCdWlH-k7tQQIT4YYuHLSlEXaVQer3g',
    appId: '1:968510000223:android:53ee584db39ae0ee59dfea',
    messagingSenderId: '968510000223',
    projectId: 'carclenx',
    databaseURL: 'https://carclenx.firebaseio.com',
    storageBucket: 'carclenx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVVDkA88M8PTTq9qU13MpA_B0S3jwCqnU',
    appId: '1:968510000223:ios:c88b4c414364aad959dfea',
    messagingSenderId: '968510000223',
    projectId: 'carclenx',
    databaseURL: 'https://carclenx.firebaseio.com',
    storageBucket: 'carclenx.appspot.com',
    androidClientId: '968510000223-06np8qaslk550qssc0mpnngpeq1mvatu.apps.googleusercontent.com',
    iosClientId: '968510000223-b3ek99lujtn1lomv518t6sm8u0dg6tj3.apps.googleusercontent.com',
    iosBundleId: 'com.carclenx.motor.shoping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVVDkA88M8PTTq9qU13MpA_B0S3jwCqnU',
    appId: '1:968510000223:ios:9e8b139c4431ac1159dfea',
    messagingSenderId: '968510000223',
    projectId: 'carclenx',
    databaseURL: 'https://carclenx.firebaseio.com',
    storageBucket: 'carclenx.appspot.com',
    androidClientId: '968510000223-06np8qaslk550qssc0mpnngpeq1mvatu.apps.googleusercontent.com',
    iosClientId: '968510000223-gp79js4i6tbphj8pmpefi0o9qsb95v50.apps.googleusercontent.com',
    iosBundleId: 'com.carclenx.motor.pexaCustomer',
  );
}
